import { Ubi } from 'types';

export const universalBasicIncomeCases: Ubi[] = [
  {
    date: {
      endDate: 'October 2019',
      startDate: 'November 2017',
    },
    effects: [],
    funding: 'European Union’s Urban Innovative Actions',
    income: {
      from: 'social benefits',
      to: 3600,
      type: 'euro monthly',
    },
    incomeAverage: 1000,
    incomeType: 'Basic Income',
    isActive: false,
    label:
      'a minimum guaranteed income with active social policies in deprived urban areas of Barcelona',
    length: 1,
    location: 'Barcelona, Spain',
    organization:
      'Department of Planning and Innovation of the Barcelona City Council’s Area of Social Rights.',
    sample: '1,000 vulnerable households',
    sampleAge: '25 - 60 years old',
    src: [],
    title: 'B-MINCOME PILOT ',
  },
  {
    date: {
      startDate: '1982',
      endDate: '2016',
    },
    effects: [
      'A 2018 paper found that the Alaska Permanent Fund "dividend had no effect on employment, and increased part-time work by 1.8 percentage points (17 percent)... our results suggest that a universal and permanent cash transfer does not significantly decrease aggregate employment."',
      'A 2019 study found "a 14% increase in substance-abuse incidents the day after the [Alaska Permanent Fund] payment and a 10% increase over the following four weeks. This is partially offset by a 8% decrease in property crime, with no changes in violent crimes. On an annual basis, however, changes in criminal activity from the payment are small. Estimated costs comprise a very small portion of the total payment, suggesting that crime-related concerns of a universal cash transfer program may be unwarranted."',
    ],
    funding: 'Alaska Permanent Fund Corporatio, surplus oil revenues',
    income: {
      from: 1000,
      to: 8288,
      type: 'USD yearly',
    },
    incomeAverage: 5180,
    isActive: false,
    incomeType: 'Basic Income',
    label: 'Alaska Permanent Fund ',
    length: 35,
    location: 'Alaska, United States',
    organization: 'Republican Governor Jay Hammond',
    sample: 'unconditional',
    sampleAge: '',
    src: ['https://www.irp.wisc.edu/publications/focus/pdfs/foc232.pdf'],
    title: 'Alaska Permanent Fund Dividend',
  },
  {
    date: {
      endDate: 'December 2009',
      startDate: 'January 2008',
    },
    effects: [],
    funding: 'Protisant Church',
    income: {
      from: 12,
      to: null,
      type: 'monthly',
    },
    incomeAverage: 12,
    incomeType: 'Basic Income',
    isActive: false,
    label: 'pilot project with basic income grant',
    length: 1,
    location: 'Nambia, Africa',
    organization: 'Namibian Basic Income Grant Coalition',
    sample: '2000 people',
    sampleAge: 'unconditional',
    src: [],
    title: 'basic income grant',
  },
  {
    date: {
      endDate: 'Present',
      startDate: 'January 2011',
    },
    effects: [],
    funding: 'Employed Women’s Association (SEWA)',
    income: {
      from: 2.2,
      to: 22,
      type: 'monthly',
    },
    incomeAverage: 13.2,
    incomeType: 'Basic Income',
    isActive: true,
    label: 'Universality, Unconditionality, Agency',
    length: 9,
    location: 'Delhi, India',
    organization: 'Employed Women’s Association (SEWA)',
    sample: '2000 people',
    sampleAge: 'unconditional',
    src: [],
    title: 'Delhi',
  },
  {
    date: {
      endDate: 'Present',
      startDate: 'January 2008',
    },
    effects: [],
    funding: '',
    income: {
      from: 2.2,
      to: 22,
      type: 'monthly',
    },
    incomeAverage: 13.2,
    incomeType: 'Basic Income',
    isActive: true,
    label: 'Universality, Unconditionality, Agency',
    length: 12,
    location: 'Madhya Pradesh, India',
    organization: 'Employed Women’s Association (SEWA)',
    sample: '2000 people',
    sampleAge: 'unconditional',
    src: [],
    title: 'Madhya Pradesh',
  },
  {
    date: {
      endDate: '2032',
      startDate: '2020',
    },
    effects: [],
    funding: 'Crowd Sourced',
    income: {
      from: 15,
      to: 30,
      type: 'monthly',
    },
    incomeAverage: 22.5,
    incomeType: 'Basic Income',
    isActive: true,
    label: 'test in Canada for free $',
    length: 3,
    location: 'Kenya, Africa',
    organization: 'GiveDirectly',
    sample: '2000',
    sampleAge: 'unconditional',
    src: [],
    title: 'GiveDirectly UBI experiment',
  },
  {
    date: {
      endDate: 'December 2018',
      startDate: 'January 2017',
    },
    effects: [],
    funding: 'Kela',
    income: {
      from: 608,
      to: null,
      type: 'euro monthly',
    },
    incomeAverage: 608,
    incomeType: 'Basic Income',
    isActive: false,
    label: 'Basic income for unemployed',
    length: 1,
    location: 'Finland',
    organization: 'Kela, the Finnish Social Insurance Institution',
    sample: '2000 low income',
    sampleAge: 'unconditional',
    src: [],
    title: 'Finland',
  },
  {
    date: {
      endDate: 'March 2019',
      startDate: 'April 2018',
    },
    effects: [],
    funding: 'Ontario Government',
    income: {
      from: 1000.31,
      to: 1415.27,
      type: 'CAD monthly',
    },
    incomeAverage: 1207.8,
    incomeType: 'Basic Income',
    isActive: false,
    label: 'Negative tax Basic Income',
    length: 1,
    location: 'Hamilton, Thunder Bay, Lindsay, Ontario, Canada',
    organization: 'Ontario Government',
    sample: '4,000 low-income',
    sampleAge: '18 - 64 years old',
    src: [],
    title: 'Negative tax Basic Income',
  },
  {
    date: {
      endDate: '2022-2024',
      startDate: 'April 2019',
    },
    effects: [
      'focus on the impact of UBI on social and physiological well-being—using both subjective and objective measures',
    ],
    funding: 'Y Combinator',
    income: {
      from: 50,
      to: 1000,
      type: 'USD monthly',
    },
    incomeAverage: 525,
    incomeType: 'Universl Basic Income',
    isActive: true,
    label: 'Private UBI from Y Combinator',
    length: 4,
    location: 'Oakland, California, United States',
    organization: 'Y Combinator Research (YCR)',
    sample: '1,000',
    sampleAge: '21 - 40 years old',
    src: [],
    title: 'Private UBI',
  },
  {
    date: {
      endDate: '2019',
      startDate: '2017',
    },
    effects: ['“Trust” experiment. primarily to take work if they find it. '],
    funding: 'Dutch Government',
    income: {
      from: 760,
      to: null,
      type: 'EURO monthly',
    },
    incomeAverage: 760,
    incomeType: 'Basic Income',
    isActive: false,
    label: 'Netherlands Basic Income',
    length: 2,
    location: 'Groningen, Tilburg, Utrecht, Wageningen, Netherlands',
    organization: 'Dutch government',
    sample: '2000 welfare recipients',
    sampleAge: '18 - 64 years old',
    src: [],
    title: 'Netherlands Basic Income',
  },
  {
    date: {
      endDate: 'TBD',
      startDate: 'TBD',
    },
    effects: [
      'not to gather rigorous data but to present useful but possibly anecdotal evidence to further UBI politically',
    ],
    funding: 'Protisant Church',
    income: {
      from: 500,
      to: null,
      type: 'USD monthly',
    },
    incomeAverage: 500,
    incomeType: 'Universal Basic Income',
    isActive: false,
    label: '',
    length: 0,
    location: 'Stockton, California',
    organization: '',
    sample: 'TBD',
    sampleAge: 'TBD',
    src: [],
    title: 'the Stockton Economic Empowerment Demonstration',
  },
  {
    date: {
      endDate: '1978',
      startDate: '1974',
    },
    effects: [
      'Residents of Dauphin, Manitoba were healthier; hospitalization rates and visits to family doctors dropped by 8.5 per cent. High school enrolment and graduation increased significantly, particularly among young men. Young mothers stayed home longer with their children. ',
    ],
    funding: 'Canadian Government',
    income: {
      from: 4000,
      to: 8884,
      type: 'CAD yearly',
    },
    incomeAverage: 6442,
    incomeType: 'Guaranteed Basic Income',
    isActive: false,
    label: 'Manitoba guaranteed annual income',
    length: 4,
    location: 'Winnipeg and Dauphin, Manitoba',
    organization: 'NDP party government',
    sample: '10,000 low income',
    sampleAge: 'randomized into a treatment group',
    src: [
      'https://albertaviews.ca/guaranteed-income/',
      'https://www.cbc.ca/archives/the-1970s-experiment-with-a-guaranteed-annual-income-1.4769701',
      'https://www.vice.com/en_us/article/nze99z/the-mincome-experiment-dauphin',
      'https://www.tandfonline.com/doi/abs/10.1080/758518991',
    ],
    title: 'Mincome',
  },
  {
    date: {
      endDate: '1972',
      startDate: '1968',
    },
    effects: [
      'The main object of the NJIME was to find out if there was any significant labor force reduction in Basic Income recipients and their main conclusion was that there was no significant reduction in workforce participation for males. Regarding the wives, the study found that “white” wives worked fewer hours, there was no significant change for “spanish speaking” and “black” wives. The study was not able to draw statistically relevant conclusions regarding mobility in and out of labor force for wives. As for husbands, the only groups of males that reduced labor hours were the very young and very old who were assigned the highest levels of subsidies. However, the young adults did tend to invest in education. The families with a lower NIT payment had more job flexibility and lower paid jobs were accepted.',
    ],
    funding: 'Office of Economic Opportunity',
    income: {
      from: '30%',
      to: '70%',
      type: 'USD negative tax off income and garuanteed income',
    },
    incomeAverage: 'Negative Income Tax',
    incomeType: 'negative tax off income and garuanteed income',
    isActive: false,
    label: 'Negative Income Tax experiment',
    length: 4,
    location: 'New Jersey and Pennsylvania, United States',
    organization: 'Mathematica',
    sample:
      '1,216 low income Black, white, and Latino, 2-parent families in urban areas',
    sampleAge: 'unconditional',
    src: [
      'https://medium.com/@sarabizarro/the-new-jersey-basic-income-experiment-of-the-60s-70s-3c9a325d6859',
      'https://econpapers.repec.org/paper/mprmprres/3b39f7503d74457ea6e37a3980762887.htm',
    ],
    title: 'The New Jersey Graduated Work Incentive Experiment',
  },
  {
    date: {
      endDate: '1972',
      startDate: '1970',
    },
    effects: [''],
    funding: 'Office of Economic Opportunity',
    income: {
      from: '30%',
      to: '70%',
      type: 'USD negative tax off income and garuanteed income',
    },
    incomeAverage: 'Negative Income Tax',
    incomeType: 'Negative Income Tax',
    isActive: false,
    label: 'Negative Income Tax experiment',
    length: 2,
    location: 'Iowa and North Carolina, United States',
    organization: 'Mathematica',
    sample:
      '809 Both 2-parent families and female-headed households in rural areas',
    sampleAge: 'unconditional',
    src: ['https://www.irp.wisc.edu/publications/sr/pdfs/sr10.pdf'],
    title: 'The Rural Income-Maintenance Experiment',
  },
  {
    date: {
      endDate: '1976',
      startDate: '1970',
    },
    effects: [''],
    funding: 'Office of Economic Opportunity',
    income: {
      from: '50%',
      to: '80%',
      type: 'USD negative tax off income and garuanteed income',
    },
    incomeAverage: 'Negative Income Tax',
    incomeType: 'Negative Income Tax',
    isActive: false,
    label: 'Negative Income Tax experiment',
    length: 6,
    location: 'Seattle and Denver, United States',
    organization: 'Mathematica',
    sample:
      '4,800 Black, white, and Latino families with at least one dependant and incomes below $11,00 for single parents, $13,000 for two parent families.',
    sampleAge: '',
    src: ['https://catalog.hathitrust.org/Record/000666543'],
    title: 'The Seattle/Denver Income-Maintenance Experiments',
  },
  {
    date: {
      endDate: '1974',
      startDate: '1971',
    },
    effects: [''],
    funding: 'Office of Economic Opportunity',
    income: {
      from: '40%',
      to: '60%',
      type: 'USD negative tax off income and garuanteed income',
    },
    incomeAverage: 'Negative Income Tax',
    incomeType: 'Negative Income Tax',
    isActive: false,
    label: 'Negative Income Tax experiment',
    length: 3,
    location: 'Seattle and Denver, United States',
    organization: 'Mathematica',
    sample: '1,799 Black households, primarily female-headed',
    sampleAge: '18 - 58',
    src: [],
    title: 'The Gary, Indiana Experiment',
  },
  {
    date: {
      endDate: 'February 2022',
      startDate: 'February 2019',
    },
    effects: [''],
    funding: 'private donors and foundations',
    income: {
      from: '416',
      to: '',
      type: 'euro monthly',
    },
    incomeAverage: '416',
    incomeType: 'Basic Income',
    isActive: true,
    label: 'sanction-free basic security experiment',
    length: 3,
    location: 'Berlin, Germany',
    organization: 'Sanktionsfrei',
    sample: '250 people',
    sampleAge: 'unconditional',
    src: [
      'https://hartz-plus.de/studie',
      'https://www.gruenderszene.de/perspektive/grundeinkommen-test-berlin',
      'https://ubi-backend-nest.colinrosati1.now.sh',
    ],
    title: 'Hartzplus',
  },
];
